{
 "title": "BBData dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instances", "query": "label_values(up, instance)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Input endpoints: max latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{instance=~\"$instance\", uri=~\"(/objects/values)|(/input/.*)\", status=\"200\"}",
     "legendFormat": "{{instance}} {{uri}}"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "description": "Number of rejected measures in the time interval selected.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ch_derlin_input_rejected_total{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "{{$__range}}"
    }
   ]
  },
  {
   "title": "Failed logins (all times)",
   "type": "stat",
   "description": "Number of failed login,  all time",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ch_derlin_login_failed_total{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Failed auth (all time)",
   "type": "stat",
   "description": "Number of failed authentication (wrong headers), all time",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ch_derlin_auth_failed_total{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "description": "number of exceptions in the time period selected",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{instance=~\"$instance\", status!=\"200\",exception!=\"None\"}[$__range]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 4 },
   "options": {
    "content": "- *rejected measures*: wrong body received in input endpoint,\n- *failed login*: wrong username/password at /login\n- *failed auth*: wrong bbuser/bbtoken \n   (using a read-only apikey on a write endpoint is not counted)"
   }
  },
  { "title": "HTTP requests (200 OK)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Throughput (requests per seconds)",
   "type": "graph",
   "description": "Throughput (requests per second): rate(timer_count[10s]) averaged over instances",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\".*((actuator)|(docs)).*\", status=\"200\", instance=~\"$instance\"}[$__rate_interval])) by (method,uri)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "graph",
   "description": "Average latency: rate(timer_sum[10s])/rate(timer_count[10s]) averaged over instances",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(http_server_requests_seconds_sum{uri!~\".*((actuator)|(docs)).*\", instance=~\"$instance\", status=\"200\"}[$__rate_interval]) / irate(http_server_requests_seconds_count{uri!~\".*((actuator)|(docs)).*\", instance=~\"$instance\", status=\"200\"}[$__rate_interval])) by (method,uri)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  { "title": "Async Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Active threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "async_executor_active_threads{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Task done",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(async_executor_completed_tasks_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Rejected measures",
   "type": "graph",
   "description": "Total number of measures rejected by the input API, summed across all instances",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "req." }
   ],
   "targets": [
    {
     "expr": "sum(increase(ch_derlin_input_rejected_total[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Non 200 status codes (with exception)",
   "type": "graph",
   "description": "Number of requests with non 200 status codes",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "req." }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{instance=~\"$instance\", uri!~\".*((actuator)|(docs)).*\", status!=\"200\", exception!=\"None\"}[$__rate_interval])) by (method,uri,status,exception)",
     "legendFormat": "{{status}} {{method}} {{uri}}: {{exception}}"
    }
   ]
  },
  {
   "title": "Non 200 status codes (no exception)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{instance=~\"$instance\", uri!~\".*((actuator)|(docs)).*\", status!=\"200\", exception=\"None\"}[$__rate_interval])) by (method,uri,status)",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{instance=~\"$instance\", exception!=\"None\"}[$__range])) by (status, exception) != 0",
     "legendFormat": "{{status}} {{exception}}"
    }
   ]
  },
  { "title": "Custom Metrics: details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "rejected (all time)",
   "type": "bargauge",
   "description": "user_id that failed authentication (wrong bbuser/bbtoken), all time",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ch_derlin_input_rejected_total{instance=~\"$instance\"}) by (object_id)",
     "legendFormat": "object_id: {{object_id}}"
    }
   ]
  },
  {
   "title": "rejected",
   "type": "bargauge",
   "description": "user_id that failed authentication (wrong bbuser/bbtoken) in the time period selected",
   "gridPos": { "h": 16, "w": 6, "x": 10, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ch_derlin_input_rejected_total{instance=~\"$instance\"}[$__range])) by (object_id) != 0",
     "legendFormat": "object_id: {{object_id}}"
    }
   ]
  },
  {
   "title": "login failed (all times)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ch_derlin_login_failed_total{instance=~\"$instance\"}) by (username)",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "auth failed (all times)",
   "type": "bargauge",
   "description": "user_id that failed authentication (wrong bbuser/bbtoken)",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ch_derlin_auth_failed_total{instance=~\"$instance\"}) by (user_id)",
     "legendFormat": "bbuser: {{user_id}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 1, "x": 0, "y": 59 }, "options": { "content": "..." } }
 ]
}